/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class connectionClient */

#ifndef _Included_connectionClient
#define _Included_connectionClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     connectionClient
 * Method:    setSocketTOS
 * Signature: (Ljava/net/Socket;)I
 */
JNIEXPORT jint JNICALL Java_connectionClient_setSocketTOS
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
